# Generated by Django 4.2.17 on 2024-12-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communities',
            new_name='Communitie',
        ),
    ]
