# Generated by Django 4.2.17 on 2024-12-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_communitie_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitie',
            old_name='name',
            new_name='title',
        ),
    ]
